M48
; DRILL file KiCad 10.0.1 date 2026-06-14T21:58:49
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-14T21:58:49+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X57.5Y-75.5
X66.5Y-75.5
X83.5Y-75.5
X92.5Y-75.5
T2
X56.5Y-65.5
X56.5Y-134.5
X93.5Y-65.5
X93.5Y-134.5
M30
